# A simple action usage
name: Build Kernel
on:
  workflow_dispatch:

jobs:
  Build-Kernel:
    strategy:
      fail-fast: false
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
    - name: Build Kernel
      uses: dabao1955/kernel_build_action@main
      with:
          kernel-url: https://github.com/Kingslayer9988/android_kernel_oplus_mt6893
          kernel-branch: susfs-154
          ccache: false
          config: cupida_defconfig
          arch: arm64
          aosp-gcc: false
          other-gcc32-url: https://github.com/LineageOS/android_prebuilts_gcc_linux-x86_arm_arm-linux-androideabi-4.9
          other-gcc32-branch: lineage-19.1
          other-gcc64-url: https://github.com/LineageOS/android_prebuilts_gcc_linux-x86_aarch64_aarch64-linux-android-4.9
          other-gcc64-branch: lineage-19.1
          aosp-clang: false
          other-clang-url: https://gitlab.com/projectelixiros/android_prebuilts_clang_host_linux-x86_clang-r468909b
          other-clang-branch: master
          ksu: false
          ksu-other: true
          ksu-url: https://github.com/rifsxd/KernelSU-Next
          ksu-version: next-susfs
          disable-lto: true
          anykernel3: true
          anykernel3-url: https://github.com/Kingslayer9988/AnyKernel3
          extra-cmd: LLVM=1 LLVM_IAS=1
